version: '3.9'
services:
  backend:
    container_name: back
    build: ./back
    ports:
      - 3001:3001
    volumes:
      - ./back/src:/back/src
    platform: linux/x86_64
    working_dir: /back
    command: sh -c "npm run migration:run:docker && npm run start:dev"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - BACK_END_PORT=3001
      - JWT_SECRET=teste
      - DB_USER=root
      - DB_PASS=financasadmin
      - DB_HOST=db
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: mysql:5.7
    container_name: database
    platform: linux/x86_64
    ports:
      - 3002:3306
    environment:
      - MYSQL_DATABASE=financas
      - MYSQL_ROOT_PASSWORD=financasadmin
      - TZ=America/Sao_Paulo
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=-03:00', '--skip-character-set-client-handshake']
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE